### ISSUE TITLE
unexpected stop of the environment "NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException"

### ISSUE THREAD

**Issue by onlytailei** [Microsoft/malmo-challenge#30]
I start several pairs of Minecraft environments in docker. Use every pair of them as a training process. However, sometimes part of the processes stop unexpectedly (others are still working).  Every process is a function just like the provided baseline or dqn code.
The output error is:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "xxxxx", line 89, in agent_factory
    obs = env.reset(agent_type)
  File "/root/malmo-challenge/ai_challenge/pig_chase/environment.py", line 382, in reset
    return super(PigChaseEnvironment, self).reset()
  File "/root/malmo-challenge/malmopy/environment/malmo/malmo.py", line 315, in reset
    (self.MAX_START_MISSION_RETRY, e))
Exception: Unable to connect after 50 tries There are not enough clients availble in the ClientPool to start this 2 agent mission.
```

output of the agent 1 minecraft:
```
[17:20:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1
[17:20:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1
[17:20:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1
[17:20:13] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1
[17:20:14] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1
[17:20:14] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$WaitingForServerEpisode:onClientTick:923]: ***Telling server we are ready - Agent_1

```

output of agent2 minecraft:
```
[16:59:48] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:queueStateChange:143]: CLIENT request state: IDLING
[16:59:48] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: IDLING
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:queueStateChange:143]: CLIENT request state: MISSION_ENDED
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: MISSION_ENDED
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$MissionEndedEpisode:sendMissionEnded:1915]: Sending mission ended message to 172.19.0.9:10583.
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:queueStateChange:143]: CLIENT request state: WAITING_FOR_SERVER_MISSION_END
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: WAITING_FOR_SERVER_MISSION_END
[16:59:49] [Thread-1565/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:49] [Thread-1565/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: MALMO_FIND_SERVER
[16:59:49] [Thread-1565/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOSmalmo1:45573
[16:59:49] [Thread-1567/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:49] [Thread-1567/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: MALMO_REQUEST_CLIENT:0.21.0:20000:
[16:59:49] [Thread-1567/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOBUSY
[16:59:49] [Thread-1569/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:49] [Thread-1569/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: <?xml version="1.0" encoding="UTF-8" standalone="no" ?><MissionInit xmlns="http://ProjectMalmo.microsoft.com" PlatformVersion="0.21.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ProjectMalmo.microsoft.com MissionInit.xsd"><Mission><About><Summary>Catch the pig!</Summary></About><ModSettings><MsPerTick>4</MsPerTick></ModSettings><ServerSection><ServerInitialConditions><Time><StartTime>6000</StartTime><AllowPassageOfTime>false</AllowPassageOfTime></Time><Weather>clear</Weather><AllowSpawning>false</AllowSpawning></ServerInitialConditions><ServerHandlers><FlatWorldGenerator destroyAfterUse="true" forceReset="false" generatorString="3;minecraft:bedrock,2*minecraft:dirt,minecraft:grass;1;village" seed=""/><DrawingDecorator><DrawCuboid type="air" x1="-10" x2="10" y1="4" y2="45" z1="-10" z2="10"/><DrawLine type="sand" x1="1" x2="7" y1="3" y2="3" z1="0" z2="0"/><DrawLine type="fence" x1="1" x2="7" y1="4" y2="4" z1="0" z2="0"/><DrawLine type="sand" x1="1" x2="7" y1="3" y2="3" z1="
[16:59:49] [Thread-1569/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOBUSY
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:queueStateChange:143]: CLIENT request state: DORMANT
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.StateMachine:setState:101]: CLIENT enter state: DORMANT
[16:59:49] [Client thread/INFO] [STDOUT]: [com.microsoft.Malmo.Utils.TCPInputPoller:clearCommands:127]: JETTISONING 0 COMMANDS
[16:59:55] [Thread-1571/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:55] [Thread-1571/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: MALMO_REQUEST_CLIENT:0.21.0:20000:
[16:59:55] [Thread-1571/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine:isReserved:154]: ==== RES:  - 6363
[16:59:55] [Thread-1571/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOOK
[16:59:55] [Thread-1573/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:55] [Thread-1573/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: MALMO_CANCEL_REQUEST
[16:59:55] [Thread-1573/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine:isReserved:154]: ==== RES: RESERVED - 19989
[16:59:55] [Thread-1573/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOOK
[16:59:57] [Thread-1575/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:443]: Received from 172.19.0.9:
[16:59:57] [Thread-1575/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:onCommand:444]: MALMO_REQUEST_CLIENT:0.21.0:20000:
[16:59:57] [Thread-1575/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine:isReserved:154]: ==== RES:  - 18283
[16:59:57] [Thread-1575/INFO] [STDOUT]: [com.microsoft.Malmo.Client.ClientStateMachine$1:reply:428]: REPLYING WITH: MALMOOK
[17:00:10] [Netty Client IO #1/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[17:00:10] [Client thread/INFO] [FML]: Applying holder lookups
[17:00:10] [Client thread/INFO] [FML]: Holder lookups applied

```

**Comment by mfuntowicz** [comment]
Hi @onlytailei,

We're currently working on it. I'll get back to this post as soon as it fixed.

Sorry for this.
Morgan

**Comment by mfuntowicz** [comment]
Hi @onlytailei,

Do you have a public Github repository to reproduce this ? 

Thanks, 
Morgan

**Comment by onlytailei** [comment]
Hi @mfuntowicz,
I will try to build one soon.
