### ISSUE TITLE
Cannot run pig_chase_human_vs_agent.py or pig_chase_baseline.py

### ISSUE THREAD

**Issue by zcleghern** [Microsoft/malmo-challenge#32]
Hello, after a fresh install of Malmo and cloning the challenge repo, I cannot seem to get the challenge working. I have both instances of malmo up and running and when i try to run either of the two above scripts I get:

> Traceback (most recent call last):
>   File "pig_chase_baseline.py", line 37, in <module>
>     from agent import PigChaseChallengeAgent, FocusedAgent
>   File "/home/zach/malmo-challenge/ai_challenge/pig_chase/agent.py", line 23, in <module>
>     from tkinter import ttk, Canvas, W
>   File "/usr/local/lib/python2.7/dist-packages/tkinter/__init__.py", line 6, in <module>
>     from Tkinter import (_cnfmerge, _default_root, _flatten, _join, _setit,
> ImportError: cannot import name _splitdict

Not sure how this error is occurring. Has anyone run into this?

**Comment by zcleghern** [comment]
changing the line
`from tkinter import ttk, Canvas, W`
to
`from Tkinter import Canvas, W`
solved this.
